arc: gdb-7.9: Do not include stdio.h and ctypes.h
For reason that I do not really understand inclusion of ctypes.h and stdio.h
causes a build failure in GDB 7.9:

    In file included from build-gnulib/import/sys/types.h:27,
                 from build-gnulib/import/stdio.h:63,
                 from ../../gdb/gdb/arc-tdep.c:167:
    /usr/include/sys/types.h:34: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or [sic]
    ../../gdb/gdb/arc-tdep.c:168:
    /usr/include/ctype.h:48: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or [sic]

That apparently has something to do with gnu-lib updades in November 2014.
The solution is to avoid inclusion of those header files.

Signed-off-by: Anton Kolesov <Anton.Kolesov@synopsys.com>